const ACCESS_TOKEN = "Access-Token";
const REFRESH_TOKEN = "Refresh-Token";
const EXPIRATION_DAYS = 14;
const REFRESH_TIME = 1000 * 60 * 14

export {
  ACCESS_TOKEN, EXPIRATION_DAYS, REFRESH_TIME, REFRESH_TOKEN
};

